version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./:/app
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./:/app
  mysql:
    image: mariadb:10.11.2
    environment:
      MYSQL_ROOT_PASSWORD: 'mypasswd'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 'testerpasswd'
      MYSQL_DATABASE: 'ricksworld'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysqldata: {}